added express-validator
OlaIstra/CI__server pull request #16
Opened 2021-03-30 10:33 UTC by OlaIstra

2021-03-31 09:28 UTC, kkirik commented on server/components/jobs/jobValidationSchema.ts
> +    branchName: {
лучше группировать валидацию body вместе

2021-03-31 09:28 UTC, kkirik commented on server/components/validation/checkErrors.ts
> +export default (req: Request, res: Response) => {
перепиши на именованный экспорт + название checkErrors не очень, для валидации req

2021-03-31 09:28 UTC, kkirik commented on server/components/validation/throwError.ts
> +export default ({ code, message, data = [] }: ThrowErrorArgs) => {
~default~

2021-04-05 12:28 UTC, kkirik requested changes

2021-04-05 12:28 UTC, kkirik commented on server/components/validation/validateRequest.ts
> +    isValidRequest && func(req, res, next);
буэ, не пиши так. Для этого даже есть отдельное правило
```
if (isValidRequest) {
  func(req, res, next)
}
```

2021-04-05 12:28 UTC, kkirik commented on server/components/validation/validateRequest.ts
> +    func: (req: Request<any>, res: Response, next: NextFunction) => void,
можно без any

2021-04-05 12:28 UTC, kkirik commented on server/components/validation/validateRequest.ts
> +    validatedRequest.forEach((item: any) => {
используй .every

2021-04-05 12:28 UTC, kkirik commented on server/components/validation/validateRequest.ts
> +            res.send({ status: 400, message: `ERROR: ${item.errors[0].msg}` });
ты должна собирать ошибки, а потом отправлять их все в 1 ответе, представь, что у тебя 10 ошибок валидации и что ты делать будешь?

2021-04-05 12:28 UTC, kkirik commented on server/components/validation/validateRequest.ts
> +            res.send({ status: 400, message: `ERROR: ${item.errors[0].msg}` });
статус пиши через enum

2021-04-05 12:28 UTC, kkirik commented on server/components/validation/validateRequest.ts
> +    validatedRequest.forEach((item: any) => {
а лучше reduce, чтобы собрать все ошибки

2021-04-05 12:39 UTC, OlaIstra commented on server/components/validation/validateRequest.ts
> +    func: (req: Request<any>, res: Response, next: NextFunction) => void,
не получается, тогда ругается в jobRouter

2021-04-05 13:10 UTC, kkirik commented on server/components/validation/validateRequest.ts
>      let isValidRequest = true;
а зачем тебе это, если ты можешь на основании длины массива определять, есть у тебя ошибки или нет?

2021-04-05 13:10 UTC, kkirik commented on server/components/validation/validateRequest.ts
> +            result.push(item.errors[0].msg);
не push, а return [...result,

2021-04-05 13:10 UTC, kkirik commented on server/components/validation/validateRequest.ts
> +    const errors = validatedRequest.reduce(function(result: any, item: any) {
напиши тип

2021-04-05 13:10 UTC, kkirik commented on server/components/validation/validateRequest.ts
> +        res.send({ status: HttpCode.BAD_REQUEST, message: `${errors}` });
Ты проверяла это?) Тут сработает приведение массива к строке, не очень тайпскриптенько, лучше приводить к строке явно

2021-04-05 13:13 UTC, OlaIstra commented on server/components/validation/validateRequest.ts
> +        res.send({ status: HttpCode.BAD_REQUEST, message: `${errors}` });
да, получается строка, с ошибками через запятую. Сделаю

2021-04-05 13:31 UTC, kkirik approved these changes

2021-04-05 13:32 UTC, merged